apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: certificate-sifon
spec:
  secretName: tls-cert
  duration: 24h
  renewBefore: 12h
  commonName: sifon.uk
  dnsNames:
  - sifon.uk
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer