apiVersion: apps/v1
kind: Deployment
metadata:
  name: sifon
  namespace: sifon
  labels:
    app: sifon
spec:
  selector:
    matchLabels:
      app: sifon
  replicas: 1
  template:
    metadata:
      labels:
        app: sifon
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: sifon
        image: martinmiles/Sifon.UK
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80