apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01  # this line is important
    certmanager.k8s.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  name: ingress-sifon
  namespace: sifon
spec:
  rules:
  - host: sifon.uk
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sifon-service
              port: 
                number: 80
  tls:
  - hosts:
    - sifon.uk
    secretName: tls-cert